Use master
GO
Create database QLTTDL
GO
Use QLTTDL
GO
Create table DanhMuc
(
	MaDanhMuc VARCHAR(10) PRIMARY KEY,
	TenDanhMuc NVARCHAR(50)
)
GO
CREATE TABLE DiemDuLich
(
	MaDiemDL VARCHAR(10) PRIMARY KEY,
	TenDiemDL NVARCHAR(100),
	MaDanhMuc VARCHAR(10) FOREIGN KEY REFERENCES DanhMuc(MaDanhMuc)
)
GO
CREATE TABLE TTDuLich
(
	MaTTDL VARCHAR(10) PRIMARY KEY,
	MaDiemDL VARCHAR(10) FOREIGN KEY REFERENCES DiemDuLich(MaDiemDL),
	DiemXuatPhat VARCHAR(10) FOREIGN KEY REFERENCES DanhMuc(MaDanhMuc),
	NgayKhoiHanh DATETIME,
	PhuongTien NVARCHAR(100),
	Gia NVARCHAR(50)
)

GO
CREATE TABLE [User]
(
	UserID VARCHAR(10) PRIMARY KEY,
	UserName VARCHAR(100) UNIQUE,
	[Password] VARCHAR(100),
	FullName NVARCHAR(100),
	Email VARCHAR(100),
	Phone VARCHAR(10),
	DateOfBirth DATE
)
